// <auto-generated />
using System;
using ADDS.PIM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADDS.PIM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PimDbContext))]
    [Migration("20260828155727_AddGroupNotificationRecipientTypeAndOutboxHeaderSplit")]
    partial class AddGroupNotificationRecipientTypeAndOutboxHeaderSplit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.ApiRequestReplayEntity", b =>
                {
                    b.Property<Guid>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalRequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReplayId");

                    b.HasIndex("Nonce")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ApiRequestReplays", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorAccountDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClientSourceIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FailureCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontendClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PersonDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyRequirementsSummary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceComponent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAccountDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetGroupDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId");

                    b.HasIndex("RequestId", "OccurredUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", b =>
                {
                    b.Property<Guid>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AllowedTtlStepSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("MaximumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinimumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiresSecondFactor")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiresTicket")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EntitlementId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PersonId", "TargetAccountId", "TargetGroupId");

                    b.ToTable("DirectEntitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_DirectEntitlements_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DomainQualifiedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabledInDirectory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithinAllowedScope")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectSid")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("AccountId");

                    b.HasIndex("DirectoryScopeId", "ObjectGuid")
                        .IsUnique();

                    b.ToTable("DirectoryAccounts", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryReconciliationFindingEntity", b =>
                {
                    b.Property<Guid>("FindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeactivatedByObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeactivatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DetectedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FindingId");

                    b.HasIndex("DirectoryScopeId");

                    b.HasIndex("IsResolved", "DetectedUtc");

                    b.HasIndex("RunId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("DirectoryReconciliationFindings", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryReconciliationRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FrontendClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RequestedByObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RunId");

                    b.HasIndex("DirectoryScopeId");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("[Status] IN (0, 1)");

                    b.ToTable("DirectoryReconciliationRuns", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", b =>
                {
                    b.Property<Guid>("DirectoryScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StableScopeIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("DirectoryScopeId");

                    b.HasIndex("StableScopeIdentifier")
                        .IsUnique();

                    b.ToTable("DirectoryScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DirectoryScopes_StableScopeIdentifier", "LEN([StableScopeIdentifier]) > 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.Fido2ChallengeEntity", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Challenge")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SatisfiedBy")
                        .HasColumnType("int");

                    b.HasKey("ChallengeId");

                    b.HasIndex("PersonId", "ExpiresUtc");

                    b.ToTable("Fido2Challenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fido2Challenges_State", "[Purpose] IN ('Registration', 'StepUp') AND [ExpiresUtc] > [CreatedUtc] AND ([ConsumedUtc] IS NULL OR ([SatisfiedBy] IN (1, 2) AND [ConsumedUtc] <= [ExpiresUtc]))");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.Fido2CredentialEntity", b =>
                {
                    b.Property<Guid>("Fido2CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aaguid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.HasKey("Fido2CredentialId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .HasFilter("[RevokedUtc] IS NULL");

                    b.ToTable("Fido2Credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fido2Credentials_State", "[SignatureCounter] >= 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupApproverEntity", b =>
                {
                    b.Property<Guid>("GroupApproverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("GroupApproverId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("TargetGroupId", "PersonId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("GroupApprovers", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupApprovers_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupNotificationRecipientEntity", b =>
                {
                    b.Property<Guid>("GroupNotificationRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupNotificationRecipientId");

                    b.HasIndex("TargetGroupId", "EmailAddress")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("GroupNotificationRecipients", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupNotificationRecipients_EmailAddress", "LEN([EmailAddress]) > 0");

                            t.HasCheckConstraint("CK_GroupNotificationRecipients_RecipientType", "[RecipientType] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupPolicyEntity", b =>
                {
                    b.Property<Guid>("GroupPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowedSecondFactorTypes")
                        .HasColumnType("int");

                    b.Property<long>("AllowedTtlStepSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DefaultTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MaximumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("MinimumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSecondFactor")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresTicket")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("GroupPolicyId");

                    b.ToTable("GroupPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupPolicies_SecondFactor", "([RequiresSecondFactor] = 0 OR [AllowedSecondFactorTypes] IN (1, 2, 3)) AND [AllowedSecondFactorTypes] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_GroupPolicies_Ttl", "[MinimumTtlSeconds] > 0 AND [MaximumTtlSeconds] >= [MinimumTtlSeconds] AND [DefaultTtlSeconds] BETWEEN [MinimumTtlSeconds] AND [MaximumTtlSeconds] AND [AllowedTtlStepSeconds] > 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MailNotificationOutboxEntity", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BccAddresses")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CcAddresses")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastFailureMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("OutboxId");

                    b.HasIndex("RequestId");

                    b.HasIndex("DeliveredUtc", "CreatedUtc");

                    b.ToTable("MailNotificationOutbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_MailNotificationOutbox_DeliveryAttempts", "[DeliveryAttemptCount] >= 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MailSettingsEntity", b =>
                {
                    b.Property<Guid>("MailSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProtectionKeyId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<int>("TlsMode")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MailSettingsId");

                    b.ToTable("MailSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_MailSettings_TlsMode", "[TlsMode] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorAccountDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetAccountDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetGroupDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("EntitlementId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PersonId", "CreatedUtc");

                    b.ToTable("MembershipRequests", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceComponent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("EntryId");

                    b.HasIndex("RequestId", "OccurredUtc");

                    b.ToTable("MembershipRequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MfaTransactionEntity", b =>
                {
                    b.Property<Guid>("MfaTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowedFactorTypes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Fido2Challenge")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyRequirementsSummary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SatisfiedBy")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("MfaTransactionId");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PersonId", "ExpiresUtc");

                    b.ToTable("MfaTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MfaTransactions_State", "[AllowedFactorTypes] IN (1, 2, 3) AND [ExpiresUtc] > [CreatedUtc] AND ([ConsumedUtc] IS NULL OR ([SatisfiedBy] IN (1, 2) AND [ConsumedUtc] <= [ExpiresUtc]))");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.NotificationTemplateEntity", b =>
                {
                    b.Property<Guid>("NotificationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationTemplateId");

                    b.HasIndex("TemplateKey")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonAccountLinkEntity", b =>
                {
                    b.Property<Guid>("PersonAccountLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MayApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("MayAuthenticate")
                        .HasColumnType("bit");

                    b.Property<bool>("MayReceivePrivileges")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonAccountLinkId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[MayAuthenticate] = 1 AND [IsActive] = 1");

                    b.ToTable("PersonAccountLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonAccountLinks_MayApproveRequiresMayAuthenticate", "[MayApprove] = 0 OR [MayAuthenticate] = 1");

                            t.HasCheckConstraint("CK_PersonAccountLinks_Purpose", "[MayAuthenticate] = 1 OR [MayReceivePrivileges] = 1");

                            t.HasCheckConstraint("CK_PersonAccountLinks_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Persons_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PurgeEventOutboxEntity", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DeliveredUtc", "CreatedUtc");

                    b.ToTable("PurgeEventOutbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurgeEventOutbox_DeliveryAttempts", "[DeliveryAttemptCount] >= 0");

                            t.HasCheckConstraint("CK_PurgeEventOutbox_EventId", "[EventId] BETWEEN 1 AND 65535");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", b =>
                {
                    b.Property<Guid>("TargetGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DomainQualifiedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("GroupPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabledForRequests")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithinAllowedScope")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectSid")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("TargetGroupId");

                    b.HasIndex("GroupPolicyId")
                        .IsUnique();

                    b.HasIndex("DirectoryScopeId", "ObjectGuid")
                        .IsUnique();

                    b.ToTable("TargetGroups", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TechnicalErrorLogEntryEntity", b =>
                {
                    b.Property<Guid>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceComponent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("ErrorId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("RequestId");

                    b.ToTable("TechnicalErrorLogEntries", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TicketReferencePatternEntity", b =>
                {
                    b.Property<Guid>("TicketReferencePatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("GroupPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TicketReferencePatternId");

                    b.HasIndex("GroupPolicyId", "Label")
                        .IsUnique();

                    b.ToTable("TicketReferencePatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketReferencePatterns_Label", "LEN([Label]) > 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TotpFactorEntity", b =>
                {
                    b.Property<Guid>("TotpFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConfirmedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ConsecutiveFailedAttempts")
                        .HasColumnType("int");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("EnrolledUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EnrollmentExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUsedTimeStep")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProtectionKeyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TotpFactorId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TotpFactors", null, t =>
                        {
                            t.HasCheckConstraint("CK_TotpFactors_State", "[ConsecutiveFailedAttempts] >= 0 AND [EnrollmentExpiresUtc] > [EnrolledUtc] AND ([IsActive] = 0 OR [ConfirmedUtc] IS NOT NULL) AND ([RevokedUtc] IS NULL OR [IsActive] = 0)");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TotpUsedTimeStepEntity", b =>
                {
                    b.Property<Guid>("TotpFactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TimeStep")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MfaTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UsedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TotpFactorId", "TimeStep");

                    b.HasIndex("MfaTransactionId");

                    b.ToTable("TotpUsedTimeSteps", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.WebSigningCertificateEntity", b =>
                {
                    b.Property<Guid>("WebSigningCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("PublicCertificateDer")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("WebSigningCertificateId");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.ToTable("WebSigningCertificates", null, t =>
                        {
                            t.HasCheckConstraint("CK_WebSigningCertificates_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.WorkerCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallerCertificateThumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CommandHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultDomainController")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResultErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResultKind")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ResultRemainingTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetAccountObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommandId");

                    b.HasIndex("Nonce")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("WorkerCommands", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.WorkerServerCertificateObservationEntity", b =>
                {
                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NotAfterUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NotBeforeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ObservedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("WasAccepted")
                        .HasColumnType("bit");

                    b.HasKey("ObservationId");

                    b.ToTable("WorkerServerCertificateObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkerServerCertificateObservations_Validity", "[NotAfterUtc] > [NotBeforeUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryReconciliationFindingEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryReconciliationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryReconciliationRunEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.Fido2ChallengeEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.Fido2CredentialEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupApproverEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupNotificationRecipientEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MailNotificationOutboxEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", null)
                        .WithMany()
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestStatusHistoryEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MfaTransactionEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonAccountLinkEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.GroupPolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TicketReferencePatternEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.GroupPolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TotpFactorEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TotpUsedTimeStepEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.MfaTransactionEntity", null)
                        .WithMany()
                        .HasForeignKey("MfaTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TotpFactorEntity", null)
                        .WithMany()
                        .HasForeignKey("TotpFactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
