// <auto-generated />
using System;
using ADDS.PIM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADDS.PIM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PimDbContext))]
    [Migration("20260801164051_AddWorkerCommandReplayProtection")]
    partial class AddWorkerCommandReplayProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorAccountDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FailureCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PersonDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceComponent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAccountDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetGroupDisplayNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TechnicalClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("EventId");

                    b.HasIndex("RequestId", "OccurredUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", b =>
                {
                    b.Property<Guid>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AllowedTtlStepSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("MaximumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinimumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiredSecurityLevel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiresSecondFactor")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiresTicket")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EntitlementId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PersonId", "TargetAccountId", "TargetGroupId");

                    b.ToTable("DirectEntitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_DirectEntitlements_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DomainQualifiedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabledInDirectory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithinAllowedScope")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectSid")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("AccountId");

                    b.HasIndex("DirectoryScopeId", "ObjectGuid")
                        .IsUnique();

                    b.ToTable("DirectoryAccounts", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", b =>
                {
                    b.Property<Guid>("DirectoryScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StableScopeIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("DirectoryScopeId");

                    b.HasIndex("StableScopeIdentifier")
                        .IsUnique();

                    b.ToTable("DirectoryScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DirectoryScopes_StableScopeIdentifier", "LEN([StableScopeIdentifier]) > 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.GroupPolicyEntity", b =>
                {
                    b.Property<Guid>("GroupPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AllowedTtlStepSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DefaultTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MaximumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("MinimumTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequiredSecurityLevel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSecondFactor")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresTicket")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("GroupPolicyId");

                    b.ToTable("GroupPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupPolicies_Ttl", "[MinimumTtlSeconds] > 0 AND [MaximumTtlSeconds] >= [MinimumTtlSeconds] AND [DefaultTtlSeconds] BETWEEN [MinimumTtlSeconds] AND [MaximumTtlSeconds] AND [AllowedTtlStepSeconds] > 0");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorAccountDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetAccountDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetGroupDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("EntitlementId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PersonId", "CreatedUtc");

                    b.ToTable("MembershipRequests", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceComponent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("EntryId");

                    b.HasIndex("RequestId", "OccurredUtc");

                    b.ToTable("MembershipRequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonAccountLinkEntity", b =>
                {
                    b.Property<Guid>("PersonAccountLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MayAuthenticate")
                        .HasColumnType("bit");

                    b.Property<bool>("MayReceivePrivileges")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonAccountLinkId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAccountLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonAccountLinks_Purpose", "[MayAuthenticate] = 1 OR [MayReceivePrivileges] = 1");

                            t.HasCheckConstraint("CK_PersonAccountLinks_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Persons_Validity", "[ValidUntilUtc] IS NULL OR [ValidUntilUtc] > [ValidFromUtc]");
                        });
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", b =>
                {
                    b.Property<Guid>("TargetGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DomainQualifiedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("GroupPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabledForRequests")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithinAllowedScope")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectSid")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("TargetGroupId");

                    b.HasIndex("GroupPolicyId")
                        .IsUnique();

                    b.HasIndex("DirectoryScopeId", "ObjectGuid")
                        .IsUnique();

                    b.ToTable("TargetGroups", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.WorkerCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallerCertificateThumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CommandHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectoryScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RequestedTtlSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetAccountObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommandId");

                    b.HasIndex("Nonce")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("WorkerCommands", (string)null);
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectEntitlementEntity", null)
                        .WithMany()
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestStatusHistoryEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.MembershipRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.PersonAccountLinkEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ADDS.PIM.Infrastructure.Persistence.Entities.TargetGroupEntity", b =>
                {
                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.DirectoryScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectoryScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADDS.PIM.Infrastructure.Persistence.Entities.GroupPolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
